/**
 * Autogenerated by Thrift Compiler (0.8.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#import <Foundation/Foundation.h>

#import "TProtocol.h"
#import "TApplicationException.h"
#import "TProtocolUtil.h"
#import "TProcessor.h"


@interface ChatMessage : NSObject <NSCoding> {
  NSString * __message;
  NSArray * __image;

  BOOL __message_isset;
  BOOL __image_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
@property (nonatomic, retain, getter=image, setter=setImage:) NSArray * image;
#endif

- (id) initWithMessage: (NSString *) message image: (NSArray *) image;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) message;
- (void) setMessage: (NSString *) message;
- (BOOL) messageIsSet;

- (NSArray *) image;
- (void) setImage: (NSArray *) image;
- (BOOL) imageIsSet;

@end

@interface UserAlreadyRegisteredException : NSException <NSCoding> {
  NSString * __message;

  BOOL __message_isset;
}

#if TARGET_OS_IPHONE || (MAC_OS_X_VERSION_MAX_ALLOWED >= MAC_OS_X_VERSION_10_5)
@property (nonatomic, retain, getter=message, setter=setMessage:) NSString * message;
#endif

- (id) initWithMessage: (NSString *) message;

- (void) read: (id <TProtocol>) inProtocol;
- (void) write: (id <TProtocol>) outProtocol;

- (NSString *) message;
- (void) setMessage: (NSString *) message;
- (BOOL) messageIsSet;

@end

@protocol ChatAPI <NSObject>
- (NSString *) addNewUser: (NSString *) username;  // throws UserAlreadyRegisteredException *, TException
- (void) sendMessage: (ChatMessage *) message : (NSString *) username : (NSString *) token;  // throws TException
@end

@interface ChatAPIClient : NSObject <ChatAPI> {
  id <TProtocol> inProtocol;
  id <TProtocol> outProtocol;
}
- (id) initWithProtocol: (id <TProtocol>) protocol;
- (id) initWithInProtocol: (id <TProtocol>) inProtocol outProtocol: (id <TProtocol>) outProtocol;
@end

@interface ChatAPIProcessor : NSObject <TProcessor> {
  id <ChatAPI> mService;
  NSDictionary * mMethodMap;
}
- (id) initWithChatAPI: (id <ChatAPI>) service;
- (id<ChatAPI>) service;
@end

@interface chatConstants : NSObject {
}
@end
